Repository marinebox/tab-killer, pull requests merged in 2021-12, with the labels that each got.

#62 ホワイトリストを追加しやすくした
  src/js/whitelist.js
  src/popup.html
Labels: enhancement

#71 ストレージAPI周りをPromiseで共通化
  src/js/history.js
  src/js/language.js
  src/js/popup.js
  src/js/utils.js
  src/js/whitelist.js
Labels: refactoring

#75 tabs周りのAPIをPromiseで共通化
  src/js/domain.js
  src/js/popup.js
  src/js/utils.js
  src/js/whitelist.js
Labels: refactoring

#78 isOverWindowsをstorageから引き出す
  src/js/popup.js
Labels: refactoring

#81 履歴一括削除機能
  src/js/history.js
  src/js/whitelist.js
  src/popup.html
Labels: enhancement

#82 履歴削除機能
  src/js/history.js
Labels: enhancement

#84 auto時の確認メッセージの修正
  src/js/history.js
  src/js/language.js
  src/js/whitelist.js
Labels: bug

#87 historyにfaviconを追加
  src/js/history.js
Labels: enhancement, UI

#90 最後の一つ消せるようにした
  src/js/history.js
Labels: bug

#91 拡張機能本体の国際化
  src/_locales/en/messages.json
  src/_locales/ja/messages.json
  src/manifest.json
Labels: enhancement

#92 ドメイン削除ボタンにfaviconを追加
  src/js/domain.js
Labels: enhancement

#94 ドメイン削除も対象ウィンドウを選べるようにした
  src/js/domain.js
  src/js/popup.js
Labels: enhancement

#96 横線追加
  src/css/popup.css
  src/popup.html
Labels: UI

#98 バッジが更新されてないバグの解消
  src/js/background.js
  src/manifest.json
Labels: bug

#100 setStorage共通化
  src/js/history.js
  src/js/language.js
  src/js/popup.js
  src/js/utils.js
  src/js/whitelist.js
Labels: refactoring

#102 history削除バグ修正
  src/js/history.js
Labels: bug

#105 initなど整理
  src/js/history.js
  src/js/language.js
  src/js/popup.js
  src/js/utils.js
  src/js/whitelist.js
Labels: refactoring

#108 favicon取得APIを変更
  src/js/domain.js
  src/js/history.js
Labels: enhancement, UI

#114 ツールバーにアイコンを追加してみた
  src/popup.html
Labels: UI

#115 全ウィンドウ対象否をアイコンでわかりやすく
  src/icon/phosphor.css
  src/js/popup.js
  src/js/utils.js
  src/popup.html
Labels: UI

#117 ショートカット機能の実装
  src/_locales/en/messages.json
  src/_locales/ja/messages.json
  src/js/background.js
  src/manifest.json
Labels: enhancement

#119 タイトルの横にメインアイコンを追加してみた
  package.json
  src/popup.html
  yarn.lock
Labels: UI
