Repository marinebox/tab-killer, pull requests merged in 2021-11, with the labels that each got.

#43 履歴、tooltip機能を追加
  src/css/popup.css
  src/popup.js
Labels: enhancement

#44 履歴追加時に同じURLを追加しないようにした
  src/popup.js
Labels: bug, enhancement

#45 tooltipがでる条件を修正
  src/popup.js
Labels: bug

#53 ESLintをもう少しちゃんと設定した
  .eslintrc.js
  package.json
  src/js/background.js
  src/js/history.js
  src/js/screenSwitch.js
  src/js/whitelist.js
  yarn.lock
Labels: enhancement

#58 ホワイトリスト未定義時に重複タブ削除が動作しない問題の修正
  .gitignore
  src/js/popup.js
Labels: bug

#59 ホワイトリストオールクリア機能
  src/js/whitelist.js
  src/popup.html
Labels: enhancement

#63 重複の中身をわかるようにした
  src/js/popup.js
Labels: enhancement
